---
- name: Deploy minha aplicação
  community.kubernetes.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: "{{ kubernetes_deployment_name }}"
        labels: "{{ kubernetes_labels }}"
        namespace: "{{ kubernetes_namespace }}"
      spec:
        replicas: "{{ kubernetes_deployment_replicas }}"
        selector:
          matchLabels: "{{ kubernetes_labels }}"
        template:
          metadata:
            labels: "{{ kubernetes_labels }}"
          spec:
            containers:
              - name: "{{ kubernetes_deployment_name }}"
                image: "{{ kubernetes_deployment_image }}"
                ports:
                  - containerPort: "{{ kubernetes_service_port }}"
  become: yes

- name: Deploy meu serviço
  community.kubernetes.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: "{{ kubernetes_service_name }}"
        namespace: "{{ kubernetes_namespace }}"
      spec:
        selector: "{{ kubernetes_labels }}"
        ports:
          - name: http
            port: "{{ kubernetes_service_port }}"
            targetPort: "{{ kubernetes_service_port }}"
        type: "{{ kubernetes_service_type }}"
  become: yes
